// <auto-generated />
using System;
using Fynex.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fynex.Infrastructure.Migrations
{
    [DbContext(typeof(FynexDbContext))]
    partial class FynexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Fynex.Domain.Entities.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 150.75m,
                            Date = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Notebooks and pens",
                            PaymentType = 1,
                            Title = "Office Supplies",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 99.90m,
                            Date = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly plan",
                            PaymentType = 3,
                            Title = "Internet",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 350.00m,
                            Date = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tech conference 2025",
                            PaymentType = 1,
                            Title = "Conference Ticket",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 120.00m,
                            Date = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Programming books",
                            PaymentType = 2,
                            Title = "Books",
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 45.50m,
                            Date = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Coffee for the team",
                            PaymentType = 3,
                            Title = "Coffee",
                            UserId = 5L
                        });
                });

            modelBuilder.Entity("Fynex.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ExpenseId")
                        .HasColumnType("bigint");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ExpenseId = 1L,
                            Value = 1
                        },
                        new
                        {
                            Id = 2L,
                            ExpenseId = 1L,
                            Value = 3
                        },
                        new
                        {
                            Id = 3L,
                            ExpenseId = 2L,
                            Value = 1
                        },
                        new
                        {
                            Id = 4L,
                            ExpenseId = 2L,
                            Value = 3
                        },
                        new
                        {
                            Id = 5L,
                            ExpenseId = 3L,
                            Value = 8
                        },
                        new
                        {
                            Id = 6L,
                            ExpenseId = 3L,
                            Value = 6
                        },
                        new
                        {
                            Id = 7L,
                            ExpenseId = 4L,
                            Value = 8
                        },
                        new
                        {
                            Id = 8L,
                            ExpenseId = 4L,
                            Value = 4
                        },
                        new
                        {
                            Id = 9L,
                            ExpenseId = 5L,
                            Value = 1
                        },
                        new
                        {
                            Id = 10L,
                            ExpenseId = 5L,
                            Value = 2
                        });
                });

            modelBuilder.Entity("Fynex.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "alice@email.com",
                            Name = "Alice",
                            Password = "hashedpassword1",
                            Role = "administrator",
                            UserIdentifier = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2L,
                            Email = "bob@email.com",
                            Name = "Bob",
                            Password = "hashedpassword2",
                            Role = "teamMember",
                            UserIdentifier = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = 3L,
                            Email = "carol@email.com",
                            Name = "Carol",
                            Password = "hashedpassword3",
                            Role = "teamMember",
                            UserIdentifier = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = 4L,
                            Email = "david@email.com",
                            Name = "David",
                            Password = "hashedpassword4",
                            Role = "teamMember",
                            UserIdentifier = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = 5L,
                            Email = "eve@email.com",
                            Name = "Eve",
                            Password = "hashedpassword5",
                            Role = "teamMember",
                            UserIdentifier = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("Fynex.Domain.Entities.Expense", b =>
                {
                    b.HasOne("Fynex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fynex.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Fynex.Domain.Entities.Expense", "Expense")
                        .WithMany("Tags")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("Fynex.Domain.Entities.Expense", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
